AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tmp Description

Parameters:
  Stage:
    Type: String
    Description: Deployment environment (e.g., dev, or test)
    AllowedValues:
      - dev
      - test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:


Resources:

   
Outputs:
